# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a specific stackage snapshot or a compiler version
resolver: lts-13.10
allow-newer: true

# User packages to be built
packages:
- .
- ../accelerate-llvm/accelerate-llvm

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps:
- git:    https://github.com/sakehl/accelerate.git
  commit: 48a65e20a43fb1a45ff38adc542cb1c79b032ad7
#  commit: d948d737683bc2f340b56319a4412505274502fc

#

- git:    https://github.com/sakehl/accelerate-llvm.git
  commit: 3d48205e008d0f0a57bffa1e6052702d6c3cad29
  subdirs:
    # - accelerate-llvm
    - accelerate-llvm-native
    - accelerate-llvm-ptx

#- git:    https://github.com/tmcdonell/accelerate-fft.git
#  commit: 782a873c000a89fd521e1ce4107daaf14bdc819d

#- git:    https://github.com/tmcdonell/lens-accelerate.git
#  commit: b74eb8098735b1ad6cff3c5655af03d3f29b9f8e

#- git: https://github.com/AccelerateHS/accelerate-io.git  
#  commit: 15c67bf66bf44bc0d6567b0d6f41338bffa178c8

- lens-accelerate-0.2.0.0
- accelerate-io-1.0.0.1
#- accelerate-fft-1.1.0.0
- git:    https://github.com/sakehl/accelerate-fft.git
  commit: 9f3b4a0852cc52abc73d1f78fe4acab85b7a052e

#- llvm-hs-4.0.0.0
#- llvm-hs-pure-4.0.0.0
- git: https://github.com/sakehl/llvm-hs.git
  commit: e733ec05c36bab0f3c4f669ada40e6a1416c7c2c
  subdirs:
    - llvm-hs
    - llvm-hs-pure

- repa-3.4.1.4

- vector-0.12.0.1

- cuda-0.10.1.0
- cufft-0.9.0.1

# Override default flag values for local packages and extra-deps
flags:
  accelerate:
    debug: true
  accelerate-fft:
    llvm-ptx: false
    llvm-cpu: false
  ska-sdp-accelerate:
    llvm-gpu: true
#  accelerate-llvm-native:
#    unsafe-checks: true
#    internal-checks: true

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.9"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
extra-include-dirs: [/mnt/cyclone/spin1/larsvdh/hdf5/include]
extra-lib-dirs: [/mnt/cyclone/spin1/larsvdh/hdf5/lib]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor

# vim: nospell
